package zenith.apps.network.data_source

import kotlinx.coroutines.withContext
import zenith.apps.core.R
import zenith.apps.core.model.Currency
import zenith.apps.core.util.CoroutineDispatchers
import zenith.apps.core.util.ResourceProvider
import zenith.apps.network.api.CurrencyApi
import zenith.apps.network.model.NetworkCurrency
import javax.inject.Inject

interface NetworkCurrencyDataSource {
    suspend fun fetchAllCurrencies(): List<NetworkCurrency>
}

internal class DefaultNetworkCurrencyDataSource @Inject constructor(
    private val currencyApi: CurrencyApi,
    private val coroutineDispatchers: CoroutineDispatchers,
    private val resourceProvider: ResourceProvider
) : NetworkCurrencyDataSource {

    override suspend fun fetchAllCurrencies(): List<NetworkCurrency> =
        withContext(coroutineDispatchers.io) {
            val response = currencyApi.fetchCurrencies()
            val codeToCurrencyName = mapOf(
                "uah" to resourceProvider.getString(R.string.uah_name),
                "usd" to resourceProvider.getString(R.string.usd_name),
                "eur" to resourceProvider.getString(R.string.eur_name),
                "try" to resourceProvider.getString(R.string.try_name),
                "aed" to resourceProvider.getString(R.string.aed_name),
                "afn" to resourceProvider.getString(R.string.afn_name),
                "all" to resourceProvider.getString(R.string.all_name),
                "amd" to resourceProvider.getString(R.string.amd_name),
                "ang" to resourceProvider.getString(R.string.ang_name),
                "aoa" to resourceProvider.getString(R.string.aoa_name),
                "ars" to resourceProvider.getString(R.string.ars_name),
                "aud" to resourceProvider.getString(R.string.aud_name),
                "azn" to resourceProvider.getString(R.string.azn_name),
                "bbd" to resourceProvider.getString(R.string.bbd_name),
                "bdt" to resourceProvider.getString(R.string.bdt_name),
                "bef" to resourceProvider.getString(R.string.bef_name),
                "bgn" to resourceProvider.getString(R.string.bgn_name),
                "bhd" to resourceProvider.getString(R.string.bhd_name),
                "bob" to resourceProvider.getString(R.string.bob_name),
                "brl" to resourceProvider.getString(R.string.brl_name),
                "bsd" to resourceProvider.getString(R.string.bsd_name),
                "bwp" to resourceProvider.getString(R.string.bwp_name),
                "byn" to resourceProvider.getString(R.string.byn_name),
                "bzd" to resourceProvider.getString(R.string.bzd_name),
                "cad" to resourceProvider.getString(R.string.cad_name),
                "cdf" to resourceProvider.getString(R.string.cdf_name),
                "chf" to resourceProvider.getString(R.string.chf_name),
                "clp" to resourceProvider.getString(R.string.clp_name),
                "cnh" to resourceProvider.getString(R.string.cnh_name),
                "cny" to resourceProvider.getString(R.string.cny_name),
                "cop" to resourceProvider.getString(R.string.cop_name),
                "crc" to resourceProvider.getString(R.string.crc_name),
                "cuc" to resourceProvider.getString(R.string.cuc_name),
                "cup" to resourceProvider.getString(R.string.cup_name),
                "cve" to resourceProvider.getString(R.string.cve_name),
                "czk" to resourceProvider.getString(R.string.czk_name),
                "djf" to resourceProvider.getString(R.string.djf_name),
                "dkk" to resourceProvider.getString(R.string.dkk_name),
                "dop" to resourceProvider.getString(R.string.dop_name),
                "dzd" to resourceProvider.getString(R.string.dzd_name),
                "eek" to resourceProvider.getString(R.string.eek_name),
                "egp" to resourceProvider.getString(R.string.egp_name),
                "ern" to resourceProvider.getString(R.string.ern_name),
                "etb" to resourceProvider.getString(R.string.etb_name),
                "fim" to resourceProvider.getString(R.string.fim_name),
                "fjd" to resourceProvider.getString(R.string.fjd_name),
                "fkp" to resourceProvider.getString(R.string.fkp_name),
                "gbp" to resourceProvider.getString(R.string.gbp_name),
                "gel" to resourceProvider.getString(R.string.gel_name),
                "ggp" to resourceProvider.getString(R.string.ggp_name),
                "ghc" to resourceProvider.getString(R.string.ghc_name),
                "gip" to resourceProvider.getString(R.string.gip_name),
                "gmd" to resourceProvider.getString(R.string.gmd_name),
                "gnf" to resourceProvider.getString(R.string.gnf_name),
                "gtq" to resourceProvider.getString(R.string.gtq_name),
                "gyd" to resourceProvider.getString(R.string.gyd_name),
                "hkd" to resourceProvider.getString(R.string.hkd_name),
                "hnl" to resourceProvider.getString(R.string.hnl_name),
                "htg" to resourceProvider.getString(R.string.htg_name),
                "huf" to resourceProvider.getString(R.string.huf_name),
                "idr" to resourceProvider.getString(R.string.idr_name),
                "ils" to resourceProvider.getString(R.string.ils_name),
                "imp" to resourceProvider.getString(R.string.imp_name),
                "inr" to resourceProvider.getString(R.string.inr_name),
                "iqd" to resourceProvider.getString(R.string.iqd_name),
                "irr" to resourceProvider.getString(R.string.irr_name),
                "isk" to resourceProvider.getString(R.string.isk_name),
                "jep" to resourceProvider.getString(R.string.jep_name),
                "jmd" to resourceProvider.getString(R.string.jmd_name),
                "jod" to resourceProvider.getString(R.string.jod_name),
                "jpy" to resourceProvider.getString(R.string.jpy_name),
                "kes" to resourceProvider.getString(R.string.kes_name),
                "kgs" to resourceProvider.getString(R.string.kgs_name),
                "khr" to resourceProvider.getString(R.string.khr_name),
                "kmf" to resourceProvider.getString(R.string.kmf_name),
                "kpw" to resourceProvider.getString(R.string.kpw_name),
                "krw" to resourceProvider.getString(R.string.krw_name),
                "kwd" to resourceProvider.getString(R.string.kwd_name),
                "kyd" to resourceProvider.getString(R.string.kyd_name),
                "kzt" to resourceProvider.getString(R.string.kzt_name),
                "lak" to resourceProvider.getString(R.string.lak_name),
                "lbp" to resourceProvider.getString(R.string.lbp_name),
                "lkr" to resourceProvider.getString(R.string.lkr_name),
                "lrd" to resourceProvider.getString(R.string.lrd_name),
                "lsl" to resourceProvider.getString(R.string.lsl_name),
                "lyd" to resourceProvider.getString(R.string.lyd_name),
                "mad" to resourceProvider.getString(R.string.mad_name),
                "mdl" to resourceProvider.getString(R.string.mdl_name),
                "mgf" to resourceProvider.getString(R.string.mgf_name),
                "mkd" to resourceProvider.getString(R.string.mkd_name),
                "mmk" to resourceProvider.getString(R.string.mmk_name),
                "mnt" to resourceProvider.getString(R.string.mnt_name),
                "mop" to resourceProvider.getString(R.string.mop_name),
                "mru" to resourceProvider.getString(R.string.mru_name),
                "mur" to resourceProvider.getString(R.string.mur_name),
                "mvr" to resourceProvider.getString(R.string.mvr_name),
                "mwk" to resourceProvider.getString(R.string.mwk_name),
                "mxn" to resourceProvider.getString(R.string.mxn_name),
                "mxv" to resourceProvider.getString(R.string.mxv_name),
                "myr" to resourceProvider.getString(R.string.myr_name),
                "mzn" to resourceProvider.getString(R.string.mzn_name),
                "nad" to resourceProvider.getString(R.string.nad_name),
                "ngn" to resourceProvider.getString(R.string.ngn_name),
                "nio" to resourceProvider.getString(R.string.nio_name),
                "nlg" to resourceProvider.getString(R.string.nlg_name),
                "nok" to resourceProvider.getString(R.string.nok_name),
                "npr" to resourceProvider.getString(R.string.npr_name),
                "nzd" to resourceProvider.getString(R.string.nzd_name),
                "omr" to resourceProvider.getString(R.string.omr_name),
                "pab" to resourceProvider.getString(R.string.pab_name),
                "pen" to resourceProvider.getString(R.string.pen_name),
                "pgk" to resourceProvider.getString(R.string.pgk_name),
                "php" to resourceProvider.getString(R.string.php_name),
                "pkr" to resourceProvider.getString(R.string.pkr_name),
                "pln" to resourceProvider.getString(R.string.pln_name),
                "pyg" to resourceProvider.getString(R.string.pyg_name),
                "qar" to resourceProvider.getString(R.string.qar_name),
                "ron" to resourceProvider.getString(R.string.ron_name),
                "rsd" to resourceProvider.getString(R.string.rsd_name),
                "rub" to resourceProvider.getString(R.string.rub_name),
                "rwf" to resourceProvider.getString(R.string.rwf_name),
                "sar" to resourceProvider.getString(R.string.sar_name),
                "sbd" to resourceProvider.getString(R.string.sbd_name),
                "scr" to resourceProvider.getString(R.string.scr_name),
                "sdg" to resourceProvider.getString(R.string.sdg_name),
                "sek" to resourceProvider.getString(R.string.sek_name),
                "sgd" to resourceProvider.getString(R.string.sgd_name),
                "shp" to resourceProvider.getString(R.string.shp_name),
                "sle" to resourceProvider.getString(R.string.sle_name),
                "sos" to resourceProvider.getString(R.string.sos_name),
                "srd" to resourceProvider.getString(R.string.srd_name),
                "srg" to resourceProvider.getString(R.string.srg_name),
                "stn" to resourceProvider.getString(R.string.stn_name),
                "svc" to resourceProvider.getString(R.string.svc_name),
                "syp" to resourceProvider.getString(R.string.syp_name),
                "szl" to resourceProvider.getString(R.string.szl_name),
                "thb" to resourceProvider.getString(R.string.thb_name),
                "tjs" to resourceProvider.getString(R.string.tjs_name),
                "tmt" to resourceProvider.getString(R.string.tmt_name),
                "tnd" to resourceProvider.getString(R.string.tnd_name),
                "top" to resourceProvider.getString(R.string.top_name)
            )
            val codeToCryptoName = mapOf(
                "eth" to resourceProvider.getString(R.string.eth_name),
                "bnb" to resourceProvider.getString(R.string.bnb_name),
                "usdt" to resourceProvider.getString(R.string.usdt_name),
                "xrp" to resourceProvider.getString(R.string.xrp_name),
                "btc" to resourceProvider.getString(R.string.btc_name)
            )
            val codeToIcon = mapOf(
                "uah" to R.drawable.ic_uah,
                "usd" to R.drawable.ic_usd,
                "eur" to R.drawable.ic_eur,
                "btc" to R.drawable.ic_btc,
                "eth" to R.drawable.ic_eth,
                "bnb" to R.drawable.ic_bnb,
                "usdt" to R.drawable.ic_usdt,
                "xrp" to R.drawable.ic_xrp,
                "try" to R.drawable.ic_try,
                "aed" to R.drawable.ic_aed,
                "afn" to R.drawable.ic_afn,
                "all" to R.drawable.ic_all,
                "amd" to R.drawable.ic_amd,
                "ang" to R.drawable.ic_ang,
                "aoa" to R.drawable.ic_aoa,
                "ars" to R.drawable.ic_ars,
                "aud" to R.drawable.ic_aud,
                "azn" to R.drawable.ic_azn,
                "bbd" to R.drawable.ic_bbd,
                "bdt" to R.drawable.ic_bdt,
                "bef" to R.drawable.ic_bef,
                "bgn" to R.drawable.ic_bgn,
                "bhd" to R.drawable.ic_bhd,
                "bob" to R.drawable.ic_bob,
                "brl" to R.drawable.ic_brl,
                "bsd" to R.drawable.ic_bsd,
                "bwp" to R.drawable.ic_bwp,
                "byn" to R.drawable.ic_byn,
                "bzd" to R.drawable.ic_bzd,
                "cad" to R.drawable.ic_cad,
                "cdf" to R.drawable.ic_cdf,
                "chf" to R.drawable.ic_chf,
                "clp" to R.drawable.ic_clp,
                "cnh" to R.drawable.ic_cnh,
                "cny" to R.drawable.ic_cnh,
                "cop" to R.drawable.ic_cop,
                "crc" to R.drawable.ic_crc,
                "cuc" to R.drawable.ic_cuc,
                "cup" to R.drawable.ic_cuc,
                "cve" to R.drawable.ic_cve,
                "czk" to R.drawable.ic_czk,
                "djf" to R.drawable.ic_djf,
                "dkk" to R.drawable.ic_dkk,
                "dop" to R.drawable.ic_dop,
                "dzd" to R.drawable.ic_dzd,
                "eek" to R.drawable.ic_eek,
                "egp" to R.drawable.ic_egp,
                "ern" to R.drawable.ic_ern,
                "etb" to R.drawable.ic_etb,
                "fim" to R.drawable.ic_fim,
                "fjd" to R.drawable.ic_fjd,
                "fkp" to R.drawable.ic_fkp,
                "gbp" to R.drawable.ic_gbp,
                "gel" to R.drawable.ic_gel,
                "ggp" to R.drawable.ic_ggp,
                "ghc" to R.drawable.ic_ghc,
                "gip" to R.drawable.ic_gip,
                "gmd" to R.drawable.ic_gmd,
                "gnf" to R.drawable.ic_gnf,
                "gtq" to R.drawable.ic_gtq,
                "gyd" to R.drawable.ic_gyd,
                "hkd" to R.drawable.ic_hkd,
                "hnl" to R.drawable.ic_hnl,
                "htg" to R.drawable.ic_htg,
                "huf" to R.drawable.ic_huf,
                "idr" to R.drawable.ic_idr,
                "ils" to R.drawable.ic_ils,
                "imp" to R.drawable.ic_imp,
                "inr" to R.drawable.ic_inr,
                "iqd" to R.drawable.ic_iqd,
                "irr" to R.drawable.ic_irr,
                "isk" to R.drawable.ic_isk,
                "jep" to R.drawable.ic_jep,
                "jmd" to R.drawable.ic_jmd,
                "jod" to R.drawable.ic_jod,
                "jpy" to R.drawable.ic_jpy,
                "kes" to R.drawable.ic_kes,
                "kgs" to R.drawable.ic_kgs,
                "khr" to R.drawable.ic_khr,
                "kmf" to R.drawable.ic_kmf,
                "kpw" to R.drawable.ic_kpw,
                "krw" to R.drawable.ic_krw,
                "kwd" to R.drawable.ic_kwd,
                "kyd" to R.drawable.ic_kyd,
                "kzt" to R.drawable.ic_kzt,
                "lak" to R.drawable.ic_lak,
                "lbp" to R.drawable.ic_lbp,
                "lkr" to R.drawable.ic_lkr,
                "lrd" to R.drawable.ic_lrd,
                "lsl" to R.drawable.ic_lsl,
                "lyd" to R.drawable.ic_lyd,
                "mad" to R.drawable.ic_mad,
                "mdl" to R.drawable.ic_mdl,
                "mgf" to R.drawable.ic_mgf,
                "mkd" to R.drawable.ic_mkd,
                "mmk" to R.drawable.ic_mmk,
                "mnt" to R.drawable.ic_mnt,
                "mop" to R.drawable.ic_mop,
                "mru" to R.drawable.ic_mru,
                "mur" to R.drawable.ic_mur,
                "mvr" to R.drawable.ic_mvr,
                "mwk" to R.drawable.ic_mwk,
                "mxn" to R.drawable.ic_mxn,
                "mxv" to R.drawable.ic_mxn,
                "myr" to R.drawable.ic_myr,
                "mzn" to R.drawable.ic_mzn,
                "nad" to R.drawable.ic_nad,
                "ngn" to R.drawable.ic_ngn,
                "nio" to R.drawable.ic_nio,
                "nlg" to R.drawable.ic_nlg,
                "nok" to R.drawable.ic_nok,
                "npr" to R.drawable.ic_npr,
                "nzd" to R.drawable.ic_nzd,
                "omr" to R.drawable.ic_omr,
                "pab" to R.drawable.ic_pab,
                "pen" to R.drawable.ic_pen,
                "pgk" to R.drawable.ic_pgk,
                "php" to R.drawable.ic_php,
                "pkr" to R.drawable.ic_pkr,
                "pln" to R.drawable.ic_pln,
                "pyg" to R.drawable.ic_pyg,
                "qar" to R.drawable.ic_qar,
                "ron" to R.drawable.ic_ron,
                "rsd" to R.drawable.ic_rsd,
                "rub" to R.drawable.ic_rub,
                "rwf" to R.drawable.ic_rwf,
                "sar" to R.drawable.ic_sar,
                "sbd" to R.drawable.ic_sbd,
                "scr" to R.drawable.ic_scr,
                "sdg" to R.drawable.ic_sdg,
                "sek" to R.drawable.ic_sek,
                "sgd" to R.drawable.ic_sgd,
                "shp" to R.drawable.ic_shp,
                "sle" to R.drawable.ic_sle,
                "sos" to R.drawable.ic_sos,
                "srd" to R.drawable.ic_srd,
                "srg" to R.drawable.ic_srd,
                "stn" to R.drawable.ic_stn,
                "svc" to R.drawable.ic_svc,
                "syp" to R.drawable.ic_syp,
                "szl" to R.drawable.ic_szl,
                "thb" to R.drawable.ic_thb,
                "tjs" to R.drawable.ic_tjs,
                "tmt" to R.drawable.ic_tmt,
                "tnd" to R.drawable.ic_tnd,
                "top" to R.drawable.ic_top
            )
            response.rates.mapNotNull { (code, rate) ->
                NetworkCurrency(
                    code = code,
                    rate = rate,
                    name = codeToCurrencyName[code] ?: codeToCryptoName[code] ?: return@mapNotNull null,
                    icon = codeToIcon[code] ?: return@mapNotNull null,
                    isCrypto = codeToCryptoName.containsKey(code)
                )
            }
        }
}